change tests to test.
it seems the folder it looks for is test. (it is inconsistent with the other folders, contracts and migrations)

Error I get when the folder is called tests:
/usr/lib/node_modules/truffle/lib/commands/test.js:37
      files = files.filter(function(file) {
                   ^

TypeError: Cannot read property 'filter' of undefined
    at /usr/lib/node_modules/truffle/lib/commands/test.js:37:20
    at /usr/lib/node_modules/truffle/node_modules/node-dir/lib/paths.js:72:25
    at FSReqWrap.oncomplete (fs.js:123:15)